### ISSUE TITLE
终端配置文件设置proxy,一劳永逸.

### ISSUE THREAD

**Issue by KarlZeo** [comwrg/FUCK-GFW#1]
在`.bash_profile`或者`.zshrc`里面.
粘贴如下形式的代码
```
export https_proxy=http://127.0.0.1:1080
export http_proxy=http://127.0.0.1:1080
export all_proxy=socks5://127.0.0.1:1080
```
可以直接让终端所有的程序都享受代理.
配合clashX之类的程序,效果更好

**Comment by langyo** [comment]
Win NT 用户怎么办呢

**Comment by comwrg** [comment]
> 在`.bash_profile`或者`.zshrc`里面.
> 粘贴如下形式的代码
> 
> ```
> export https_proxy=http://127.0.0.1:1080
> export http_proxy=http://127.0.0.1:1080
> export all_proxy=socks5://127.0.0.1:1080
> ```
> 可以直接让终端所有的程序都享受代理.
> 配合clashX之类的程序,效果更好

嗯, 一开始我是这样的, 但是呢, 有的软件是不支持http_proxy的, 而且, 有的时候, 有些软件我并不需要代理, 所以... 我还是选择这样配置

**Comment by comwrg** [comment]
> Win NT 用户怎么办呢

我一般在Windows下面是全局代理

**Comment by KarlZeo** [comment]
> Win NT 用户怎么办呢

我不用Windows啊 doge

**Comment by comwrg** [comment]
> > Win NT 用户怎么办呢
> 
> 我不用Windows啊 doge

我是回复上面那位
