### ISSUE TITLE
建议规范README.md格式，并添加toc

### ISSUE THREAD

**Issue by HaodongZou** [comwrg/FUCK-GFW#16]
README.md内容不断增长，格式混乱查找起来很不方便。建议能够将各种软件/工具分类在不同级目录下，并给出Contribute规范。

并且添加TOC（Table of Content)，鉴于GitHub不支持MarkDown toc语法，可以使用GitHub Action TOC Generator https://github.com/marketplace/actions/toc-generator

**Comment by Craftsman98** [comment]
或者换一种思路，将每个软件配置方法放进单独的README.md中
